services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      - TZ=Europe/Kyiv
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=genesisStore
      
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/genesisStore?sslmode=disable
      - MAILER_HOST=mailhog
    depends_on:
      - postgres
      - mailhog
    command: [ "/app/main" ]